### ISSUE TITLE
Prevent autoscroll on close

### ISSUE THREAD

**Issue by aulneau** [francoischalifour/autocomplete.js#61]
Hi there!

Been playing around with the react component and it's great, but I have noticed that [this line](https://github.com/francoischalifour/autocomplete.js/blob/next/packages/docsearch-react/src/DocSearchModal.tsx#L296) is causing issues when the user selects an entry that is a hash, as it navigates, scrolls and then scrolls again to the top. It'd be great to be able to disable this functionality.

**Comment by francoischalifour** [comment]
Hey @aulneau—thanks for reporting this issue.

It seems like this happens because you unmount the `DocSearchModal` component on every page change. Do you have a reproduction somewhere?

Thanks!

**Comment by aulneau** [comment]
Sure -- that is correct. [You can see it here.](https://github.com/blockstack/docs.blockstack/blob/feat/next/src/components/search.tsx#L79-L87)

**Comment by francoischalifour** [comment]
Does that work if you pass `initialScrollY`? ([see example](https://github.com/facebook/docusaurus/blob/1083454dbde3186a0ad30ed6eedf4e8fad9c917e/packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js#L91))

**Comment by aulneau** [comment]
ah my bad, tried to use a hook that gives the scrollY and it was lagging, but using `window.scrollY` directly works. Thanks!
