### ISSUE TITLE
[DocSearch v3] opening shortcuts take precedence on typing

### ISSUE THREAD

**Issue by s-pace** [francoischalifour/autocomplete.js#63]
# Issue:

When the focus is on an input and one type the key `/`, the modal will open since `/` is a shortcut to open the modal. This degrades the overall user experience and interfere with other usage. 

## Example:
 Go to [the application form of DocSearch](https://docsearch.algolia.com/docs/apply/), select the URL input and type `/`. This will open the modal and breaks the typing experience.

## Deps:

This issue impacts `@docsearch/react": "1.0.0-alpha.24` and higher.

[Issue raised by a DocSearch user]( https://secure.helpscout.net/conversation/1244319804/280808?folderId=696679).

## TODO:
- [x]  Follow up on the dedicated thread once this issue is merged

**Comment by francoischalifour** [comment]
Fixed in 6118725dda6a3c0fc92ec478923c6b3187a43ad7. Releasing now.
